### ISSUE TITLE
Connection to svn server timed out

### ISSUE THREAD

**Issue by jritzi** [masterkain/classic_pagination#1]
```
$ script/plugin install svn://errtheblog.com/svn/plugins/classic_pagination
svn: Can't connect to host 'errtheblog.com': Connection timed out
```

**Comment by masterkain** [comment]
script/plugin install git://github.com/masterkain/classic_pagination.git

**Comment by jritzi** [comment]
Great, thanks! You might want to update the instructions in the README so people who find this project know how to install it.
